# Architecture
model: fvit
image_size: 32
patch_size: 8
num_layers: 4
num_heads: 8
hidden_dim: 64
expansion: 4

# Dataset
dataset: CIFAR10

# HyperParameters
epochs: 8
batch_size: 8
learning_rate: 0.0001
scheduler: False
num_workers: 1
weighted_loss: False
early_stop_tolerance: 8
clip: 1

# Misc
debug: False
augment: False
