
# Architecture
model: vit
input_size: 224
patch_size: 8
num_layers: 4
num_heads: 8
hidden_dim: 64
expansion: 4

# Dataset
dataset: CIFAR10

# HyperParameters
epochs: 8
batch: 8
learning_rate: 0.0001
weighted_loss: True
scheduler: False
num_workers: 1
early_stop_tolerance: 8

# Misc
augment: False
