# Architecture
model: fvit_monolith
image_size: 32
base_patch_size: 8
scale_factors: [1, 2]
layer_config: [1, 0]
num_heads: 4
hidden_dim: 32
expansion: 4

# Dataset
dataset: CIFAR10

# HyperParameters
epochs: 2
batch_size: 16
learning_rate: 0.0001
scheduler: True
num_workers: 1
weighted_loss: True
early_stop_tolerance: 8

# Misc
augment: False
