# Architecture
model: fvit_spectral_multiscale
image_size: 32
base_patch_size: 8
scale_factors: [0.25, 0.5, 1, 2]
num_layers: 8
num_heads: 8
hidden_dim: 64
expansion: 4

# Dataset
dataset: CIFAR10

# HyperParameters
epochs: 8
batch_size: 8
learning_rate: 0.0001
scheduler: False
num_workers: 1
weighted_loss: False
early_stop_tolerance: 8

# Misc
# debug: 3
augment: False